// lang.js
export const languages = {
    en: {
        greeting: 'Hello',
        CompanyName: 'Zhejiang XX Company',
        Features: 'Features',
        About: 'About',
        Services: 'Services',
        Gallery: 'Gallery',
        Contact: 'Contact',
        LearnMore: 'Learn More',
        WhyChooseUs: 'Why Choose Us',
        ContactInfo: 'Contact Info',
        Address: 'Address',
        PhoneNumber: 'Phone Number',
        Email: 'Email',
        ContactGuidelines: 'Please fill out the form below to send us an email and we will get back to you as soon as possible!',
        Send: 'Send',
    },
    zh: {
        greeting: '你好',
        CompanyName: '浙江XX竹制品有限公司',
        Features: '公司特色',
        About: '关于我们',
        Services: '公司服务',
        Gallery: '产品展示',
        Contact: '联系我们',
        LearnMore: '了解更多',
        WhyChooseUs: '为什么选择我们',
        ContactInfo: '联系方式',
        Address: '地址',
        PhoneNumber: '电话',
        Email: '邮箱',
        ContactGuidelines: '请填写下面的表单以发送电子邮件给我们，我们会尽快给您回复！',
        Send: '发送',
    },
};